import React from 'react'
import geologia1 from '../../assets/geologia.png'

const Geologia = () => {
    return (
        <section className="Marco_referencia_section">
            <h2 className="MarcoReferencia_title">Geología</h2>
            <h3 className='MarcoReferencia_subtitle'>Geología Regional</h3>
            <p className="MarcoReferencia_paragraph">El municipio de la Unión se encuentra en Plancha 167 del Servicio Geológico Colombiano (SGC), y en esta se aprecia que a escala regional se encuentran 6 unidades litológicas principales:</p>
            <figure className="MarcoReferencia_img">
                <img src={geologia1} alt="Mapa geomorfologico del municipio La Unión" />
                <figcaption>Recorte de la plancha geológica 167 del SGC (Plancha Sonsón)</figcaption>
            </figure>
            <h4 className='MarcoReferencia_h4'>Migmatitas [Pmi] - <span>(Precámbrico - Paleozoico Temprano)</span></h4>
            <p className="MarcoReferencia_paragraph">Esta unidad se dividó en dos grupos: neises cuarzo-feldespáticos de características ígneas (ortoneises) y neises aluminicos (paraneises). También se incluyen zonas esquistosas y anfibolitas cuyo espesor no es mayor a 5 m.</p>
            <p className="MarcoReferencia_paragraph">Cubren un área de 170 Km<sup>2</sup> en la Plancha 167, cuadrículas A-1 a 6, B-1 a 6, C-1 a 6 y D-1 a 6. La myor parte de las rocas de esta unidad se encuentran intensamente meteorizadas y afloramientos de roca fresca solo se encuentran en el cauce de quebradas y ríos donde la erosión ha eliminado la cubierta de roca meteroizada. Debido a las variaciones en la estructura del cuerpo de las migmaticas, las características texturales de palesoma y del neosoma varían considerablemente, aunque por lo general la composición es bastante homogénea, especialmente en el paleosoma.</p>
            <p className="MarcoReferencia_paragraph">El leucosoma, parte clara del neosoma, tiene textura hipioblástica y está compuesto por cuarzo y plagioclasa. El cuarzo es ahnedral y se presenta de disitntas maneras: gregado redondeado que bordea, agregado irregular intersicial y/o cuarzo de reemplazo. La plagioclasa, de composición variable entre An<sub>8</sub> y An<sub>30</sub>, tiene por lo general formas más isómetricas hasta tabulares especialmente en las zonas pegmatiticas. La compisicón varía de ortosa a microclina. En el leucosoma de composición granítica, son abundantes zonas de pertita y mirmequita.</p>
            <p className="MarcoReferencia_paragraph">La compisición y la textura del melanosoma son mucho más variables que las del leucosoma y está constituido esencialmente por biotita, granate, sillimanita, andalucita sericitizada, cordierita y accesorios como zircón, apatito y minerales opacos.</p>

            <h4 className='MarcoReferencia_h4'>Esquistos Cuarzo-Sericíticos [Pes] - <span>(Paleozoico Medio - Paleozoico Tardío)</span></h4>
            <p className="MarcoReferencia_paragraph">Conocidos como en el campo como esquistos negros debido a su color, se encuentran distribuidos en cuatro grandes áreas así: sur de Montebello en las quebradas Juntas y Balsos como una franja, sur de la Unión en el Río Aures como afloramiento continuo de 350 Km, sureste de la Plancha 187 en el Río Pensilvania como franja y en la parte alta del Río Perrillo como un gran techo de forma elongada.</p>
            <p className="MarcoReferencia_paragraph">Los esquistos cuarzo-sericíticos son rocas finamente laminadas en capas de 3 a 5 mm de espesor, por lo general replegados y con venas de cuarzo lechoso de 0,1 a 10 cm de espesor paralelas a la foliación y que se acomodan, por lo general, a la forma de los plegamientos. La roca está compuesta por cuarzo-sericíta, con cantidades menores de clorita, biotita, grafito, plagioclasa y como accesorios comunes turmalina, zircón, apatito y minerles opacos.Presenta por lo general una buena segregación metámorfica, definida por capas de 1 a 3 mmde espesor de micas y grafito, separadas por bandas de cuarzo granoblástico.</p>
            <p className="MarcoReferencia_paragraph">La estructura de esquistos, es localmente néisica, hasta pizarrosa pasando por filitas, mientras que en la composición muestra cambios transicionales a cuarcitas, por aumento en el contenido de cuarzo, a esquistos verdes por aumento en el contenido de clorita, y a esquistos micáceos por el aumento en el contenido de muscovita.</p>

            <h4 className='MarcoReferencia_h4'>Esquistos Verdes [Pev] - <span>(Paleozoico Medio - Paleozoico Tardío)</span></h4>
            <p className="MarcoReferencia_paragraph">En conjunto estos esquistos se distinguen por su color verdoso en tonos claros y oscuros; son rocas macizas con esquistosidad bien definida, que se confunde con los planos de diaclasamiento cuando son ricas en anfíbol-epidota y se van haciendo finamente laminadas, con estructura filítica, a medida que estos minerales son reemplazados por clorita. Esto puede observarse claramente sobre el Río Buey, abajo de Mesopotamia (Pl. 167, D-6). Microscópicamente tienen textura nematoblástica a hipidioblástica con bandeamiento composicional definido por capas de albita de 1 mm más o menos, separadas por capas de igual espesor de actinolita, epidota y/o clorita.Como minerales accesorios se encuentran calcita, esfena, cuarzo, magnetita, pirita y ocasionalmente mica blanca.</p>
            <p className="MarcoReferencia_paragraph">Cerca al contacto con los batolitos Antioqueño y de Sonsón, existen zonas de esquistos verdes porfiroblásticos y de cornubianitas hornbléndicas, ocasionalmente con diópsido y granate, provenientes de estos mismos esquistos. La deficiencia de sílice, el exceso en magnesio y calcio y además su alternancia concordante con esquistos cuarzo sericíticos, cuyo origen es claramente sedimentario, hace pensar que los esquístos verdes se originaron en eventos volcánicos que alternaron con la depositación de sedimentos en una cuenca geosinclinal. Esta secuencia fue sometida a un metamorfismo regional de bajo grado, dando origen a las intercalaciones de esquístos cuarzo-sericíticos provenientes de los sedimentos y de esquistos verdes provenientes de los derrames volcánicos.</p>

            <h4 className='MarcoReferencia_h4'>Esquistos Intercalados [Pei] - <span>(Paleozoico Medio - Paleozoico Tardío)</span></h4>
            <p className="MarcoReferencia_paragraph">En la parte noroeste del área de la Plancha 167 son comunes zonas de esquistos cuarzo-sericíticos y de esquistos verdes intercalados en capas concordantes, cuyo espesor varia entre unos pocos centímetros y varios metros, siendo díficil determinar cuál de ellos predomina en el área.</p>
            <p className="MarcoReferencia_paragraph">Estas zonas están caracterizadas en el campo por la alternancia de capas negras finamente laminadas y de capas verdes por lo general macizas, ocasionalmente estas áreas están marcadas por zonas de transición donde va disminuyendo el contenido de grafito en el esquisto cuarzo-sericítico y aumentando el de clorita para dar origen a esquistos de cuarzo-cloria-sericíta que no representan ni verdaderos esquistos verdes ni típicos esquistos cuarzo-sericíticos.</p>

            <h4 className='MarcoReferencia_h4'>Anfibolitas [Pa] - <span>(Paleozoico Medio - Paleozoico Tardío)</span></h4>
            <p className="MarcoReferencia_paragraph">Aunque parece existir más de una edad y/o origen para los diversos cuerpos de anfibolitas que se encuentran en el área, se consideran en conjunto debido a la falta de edades radiométricas y/o análisis químicos suficientes que permitan hacer una diferenciación. La estructura de la anfibolita varía entre neísica y esquistosa, a veces maciza con intenso diaclasamiento, bandeada por segregación metamórfica diferencial; estructuras migmatíticas se observaron cerca a los contactos con los cuerpos Ígneos (carretera La Ceja- La Unión, y Quebrada la Cristalina).</p>
            <p className="MarcoReferencia_paragraph">La roca fresca es de color negro a verde oscuro, tomando colores más claros cuando la plagiociasa está sausuritizada. Es una roca por lo general resistente a la meteorización, dando mejores afloramientos que los otros tipos de rocas y formando salientes topográficas notorias en los alrededores de La Ceja (A-3, 4). Al meteorizarse da una saprolita residual característica de color rojizo. La textura varía de granoblástica gruesa a fina y algunas veces nematoblástica especialmente en los silos asociados a las migmatitas; el tamaño del grano varía entre 0.3y 1,5 mm. Efectos térmicos, debidos a las intrusiones ígneas en el área, produjeron un metamorfismo de contacto en las anfibolitas, caracterizado por la aparición de diópsido y localmente de granate con reagrupación de los minerales, dando una textura hornfélsica diferente a la de las anfibolitas producidas por metamorfismo regional, donde predominan texturas nematoblásticas con bandas granoblásticas.</p>
            <p className="MarcoReferencia_paragraph">Las anfibolitas están compuestas esencialmente por hormblenda, plaglociasa, con cantidades mejores de accesorios y localmente con diópsido. La homblenda es el constituyente esencial, formando entre 50 y 76% de la roca, por lo general fresca, poikiloblástica, con inclusiones de plagioclasa y apatito, a veces cataclásticas.</p>

            <h4 className='MarcoReferencia_h4'>Cupula de La Unión [Kcdlu] - <span>(Cretáceo Tardío)</span></h4>
            <p className="MarcoReferencia_paragraph">Este cuerpo tiene forma irregular con adelgazamiento en su extremo sureste, con una extensión total de 72 km2 y está localizado en A-5, 6; B-5, 6; C6, 7 de la Plancha 167, con un pequeño apófisis de 1 km2 de forma elongada que aflora a lo largo de la Quebrada Rumazón (Pl. 167, D-1). Por lo general está topográficamente más alto que el afloramiento principal del Batolito Antioqueño, al cual aparentemente está relacionado genéticamente. La mayor parte de la roca muestra una intensa meteorización, produciendo una arcilla caolinítica de color claro. Afloramientos de roca relativamente fresca solo se encuentran en las quebradas La Esperanza (Pl. 167, C-7), Potal, Chupadero, Rumazón y en pequeñas canteras en la carretera La Unión - Mesopotamia (Pl. 167, B-5; D-6).</p>
            <p className="MarcoReferencia_paragraph">La roca dominante es de grano medio, color gris claro moteada de negro, equigranular maciza, ligeramente cataclástica en las quebradas 'Potal y La Esperanza y de composición grenodiorita a cuarzodiorita pobre en ferromagnesianos. Presenta cuarzo anhedral formando mosaicos finos, feldespato pótasico abundante (microclina y ortosa), plagioclasa (An26 - An44) con fracturamiento irregular y bien maclada, y biotita mayoritariamente cloritizada que rara vez excede el 10% de la roca. Como minerales accesorios aparecen muscovita (2-3%), por lo general asociada a biotita y probablemente de origen hidrotermal, magnetita, edpitoa, zircón, rutilo y apatito.</p>
        </section>
    )
}

export default Geologia